### ISSUE TITLE
error: passing argument 2 of ‘send_sig_info’ from incompatible pointer type 

### ISSUE THREAD

**Issue by patcrysdale** [markoneill/trustbase-linux#3]
Hi,

We're Ph.D. candidates in Canada working on testing and improving this project shown in USENIX. We love the idea but just can't get it to run. 

We tried with Raspberry Pis and ran into some issues installing. So we decided to download Fedora and try it there. It was easier to get going to on Fedora but we still ran into the same errors that seem to be issues in C language compilation.

Shown below is the output of "Make" that we ran after cloning your repository. Would you have any advice? 

[root@localhost parallels]# cd trustbase-linux/
[root@localhost trustbase-linux]# make
make -C /lib/modules/5.7.11-200.fc32.x86_64/build M=/home/parallels/trustbase-linux modules
make[1]: Entering directory '/usr/src/kernels/5.7.11-200.fc32.x86_64'
  CC [M]  /home/parallels/trustbase-linux/loader.o
/home/parallels/trustbase-linux/loader.c: In function ‘stop_task’:
/home/parallels/trustbase-linux/loader.c:143:24: error: passing argument 2 of ‘send_sig_info’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  143 |  send_sig_info(signal, &sinfo, task);
      |                        ^~~~~~
      |                        |
      |                        struct siginfo *
In file included from /home/parallels/trustbase-linux/loader.c:6:
./include/linux/sched/signal.h:331:31: note: expected ‘struct kernel_siginfo *’ but argument is of type ‘struct siginfo *’
  331 | extern int send_sig_info(int, struct kernel_siginfo *, struct task_struct *);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:267: /home/parallels/trustbase-linux/loader.o] Error 1
make[1]: *** [Makefile:1732: /home/parallels/trustbase-linux] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.7.11-200.fc32.x86_64'
make: *** [Makefile:100: trustbase] Error 2
[root@localhost trustbase-linux]#

**Comment by jordan9001** [comment]
Looks like the function signature for send_sig_info changed starting in kernel 4.20
Some ifdef version magic could fix it.
Or struct siginfo is the same as kernel_siginfo plus padding right now, so a cast would work in this case. But that might not be as neat for future changes.

**Comment by patcrysdale** [comment]
Issue resolved by using much older Kernels. I was able to get it to compile by using a stock version of Fedora 25. But more modern OSes don't seem to like it as much.
